preset: laravel

finder:
  exclude:
    - "tests"
    - "node_modules"
    - "storage"
    - "vendor"
    - "scripts"
  not-name:
    - "AcceptanceTester.php"
    - "FunctionalTester.php"
    - "UnitTester.php"